# Generated by Django 2.1.5 on 2019-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('appId', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('stack', models.TextField(max_length=2000)),
            ],
        ),
    ]
